server:
  port: 8082
  servlet:
    context-path: /kalah
spring:
  datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
#      url: jdbc:mysql://localhost:3306/kalah
#      username: root
#      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: ERROR
    com.rebound: INFO

